"""Export service for Questlog."""

import csv
import datetime as dt
import json
import logging
from pathlib import Path
from typing import Any

import requests

from questlog.config import QuestlogConfig

logger = logging.getLogger("questlog")


class ExportService:
    """Service for exporting questlog data."""

    def __init__(self, config: QuestlogConfig):
        """Initialize export service.

        Args:
            config: Questlog configuration.
        """
        self.config = config

    def sessionize(self, rows: list[dict], grace_gap: int | None = None) -> list[dict]:
        """Group entries into sessions based on time gaps.

        Args:
            rows: List of entry dictionaries.
            grace_gap: Seconds between entries to consider same session.
                       Defaults to config value.

        Returns:
            List of session dictionaries.
        """
        if grace_gap is None:
            grace_gap = self.config.grace_gap_seconds

        sessions = []
        cur = None
        last_ts = None
        for r in rows:
            t = dt.datetime.fromisoformat(r["ts"])
            key = (r["project"], r["app"], r["coarse_task"])
            if cur is None:
                cur = {"start": t, "end": t, "key": key, "items": [r]}
                last_ts = t
                continue
            delta = (t - last_ts).total_seconds()
            if key == cur["key"] and delta <= grace_gap:
                cur["end"] = t
                cur["items"].append(r)
            else:
                sessions.append(cur)
                cur = {"start": t, "end": t, "key": key, "items": [r]}
            last_ts = t
        if cur:
            sessions.append(cur)
        return sessions

    def export_markdown(self, conn, date: str) -> Path:
        """Export a daily Markdown timeline.

        Args:
            conn: Database connection.
            date: Date in YYYY-MM-DD format.

        Returns:
            Path to exported file.
        """
        cur = conn.execute(
            """
            SELECT id, ts, app, window_title, project, coarse_task, summary, confidence
            FROM entries
            WHERE date(ts) = ?
            ORDER BY ts ASC
        """,
            (date,),
        )
        rows = [dict(r) for r in cur.fetchall()]

        sessions = self.sessionize(rows)

        md_lines = [f"# Quest Log - {date}", ""]
        for s in sessions:
            proj, app, task = s["key"]
            start = s["start"].strftime("%H:%M:%S")
            end = s["end"].strftime("%H:%M:%S")
            md_lines.append(
                f"## {start}-{end} • {task or 'Unknown'} • {proj or 'Unknown'} • {app}"
            )
            md_lines.append("")
            for it in s["items"]:
                t = dt.datetime.fromisoformat(it["ts"]).strftime("%H:%M:%S")
                md_lines.append(
                    f"- {t} - {it['summary']} *(conf: {it['confidence']:.2f})*"
                )
            md_lines.append("")

        out_dir = Path("exports")
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / f"questlog_{date}.md"
        out_path.write_text("\n".join(md_lines))
        return out_path

    def export_csv(self, conn, date: str) -> Path:
        """Export a daily CSV.

        Args:
            conn: Database connection.
            date: Date in YYYY-MM-DD format.

        Returns:
            Path to exported file.
        """
        cur = conn.execute(
            """
            SELECT ts, app, window_title, project, coarse_task, summary, confidence
            FROM entries
            WHERE date(ts) = ?
            ORDER BY ts ASC
        """,
            (date,),
        )
        rows = [dict(r) for r in cur.fetchall()]

        out_dir = Path("exports")
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / f"questlog_{date}.csv"
        with open(out_path, "w", newline="") as f:
            writer = csv.DictWriter(
                f,
                fieldnames=[
                    "ts",
                    "app",
                    "window_title",
                    "project",
                    "coarse_task",
                    "summary",
                    "confidence",
                ],
            )
            writer.writeheader()
            for r in rows:
                writer.writerow(r)
        return out_path

    def generate_hour_summary(self, conn, start_time: dt.datetime) -> str:
        """Generate an LLM summary of activities within a one-hour window.

        Args:
            conn: Database connection.
            start_time: Start datetime for the hour window.

        Returns:
            Summary text generated by LLM.
        """
        end_time = start_time + dt.timedelta(hours=1)

        # Handle timezone-aware datetime comparison
        start_str = start_time.isoformat()
        end_str = end_time.isoformat()

        cur = conn.execute(
            """
            SELECT id, ts, app, window_title, project, coarse_task, summary, confidence, json
            FROM entries
            WHERE ts >= ? AND ts < ?
            ORDER BY ts ASC
            """,
            (start_str, end_str),
        )
        rows = [dict(r) for r in cur.fetchall()]

        if not rows:
            return f"No entries found for {start_time.strftime('%Y-%m-%d %H:00')}"

        # Build context for LLM
        activities = []
        for r in rows:
            ts = dt.datetime.fromisoformat(r["ts"])
            activities.append({
                "time": ts.strftime("%H:%M:%S"),
                "app": r["app"],
                "task": r["coarse_task"],
                "summary": r["summary"],
                "project": r["project"],
            })

        # Try to get full entry details from JSON
        for i, r in enumerate(rows):
            if r.get("json"):
                try:
                    entry_data = json.loads(r["json"])
                    if "clues" in entry_data:
                        activities[i]["clues"] = entry_data["clues"]
                    if "artifacts" in entry_data:
                        activities[i]["artifacts"] = entry_data["artifacts"]
                except Exception:
                    pass

        # Build prompt
        activities_text = "\n".join([
            f"- {a['time']} | {a['app']} | {a['task']} | {a['summary']} | Project: {a.get('project', 'Unknown')}"
            for a in activities
        ])

        prompt = f"""You are writing a neutral restart brief for a one-hour activity window. Help the user recover context without judging their output or attention.

Time Window: {start_time.strftime('%Y-%m-%d %H:00')} to {end_time.strftime('%H:00')}

Activities ({len(activities)} entries):
{activities_text}

Generate a brief that:
1. Identifies the main thread or theme
2. Lists concrete work items, decisions, or artifacts visible in the activity
3. Notes context switches or transitions neutrally
4. Calls out possible open loops or unclear items
5. Suggests one small restart point

Avoid scores, attention judgments, or moral language. Format as a brief paragraph followed by bullets."""

        # Try LLM summarization
        cfg_dict = self.config.to_dict()
        if cfg_dict.get("ollama", {}).get("enabled", False):
            try:
                endpoint_cfg = cfg_dict["ollama"].get("endpoint", "http://localhost:11434")
                def _join(u: str, path: str) -> str:
                    return u.rstrip("/") + path
                gen_url = endpoint_cfg if endpoint_cfg.endswith("/api/generate") else _join(endpoint_cfg, "/api/generate")

                summarization_cfg = cfg_dict["ollama"].get("summarization", {})
                model = summarization_cfg.get("model", "deepseek-r1:7b-qwen-distill-q4_K_M")

                gen_payload = {
                    "model": model,
                    "prompt": prompt,
                    "stream": False,
                }

                resp = requests.post(gen_url, json=gen_payload, timeout=30)
                resp.raise_for_status()

                response_text = (resp.json() or {}).get("response", "")
                if response_text:
                    return response_text.strip()
            except Exception as e:
                logger.warning("LLM summary generation failed: %s", e)

        # Fallback: simple text summary
        projects = set(a.get("project") for a in activities if a.get("project"))
        tasks = set(a.get("task") for a in activities if a.get("task"))
        apps = set(a.get("app") for a in activities if a.get("app"))

        summary_lines = [
            f"Restart Brief: {start_time.strftime('%Y-%m-%d %H:00')} to {end_time.strftime('%H:00')}",
            f"",
            f"Total activities: {len(activities)}",
            f"Projects: {', '.join(sorted(projects)) or 'Unknown'}",
            f"Tasks: {', '.join(sorted(tasks)) or 'Unknown'}",
            f"Apps: {', '.join(sorted(apps)) or 'Unknown'}",
            f"",
            f"Recent activity:",
        ]
        summary_lines.extend([f"  {a['time']} - {a['summary']}" for a in activities[:10]])
        if len(activities) > 10:
            summary_lines.append(f"  ... and {len(activities) - 10} more")
        if activities:
            summary_lines.extend(
                [
                    "",
                    f"Restart point: Return to {activities[-1]['summary']}",
                ]
            )

        return "\n".join(summary_lines)
